src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="array")
     */
    private $roles;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentary", mappedBy="user")
     */
    private $commentaries;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    //Implementations
    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Commentary[]
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setUser($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->contains($commentary)) {
            $this->commentaries->removeElement($commentary);
            // set the owning side to null (unless already changed)
            if ($commentary->getUser() === $this) {
                $commentary->setUser(null);
            }
        }

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/DictionaryController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Commentary;
use App\Entity\Term;
use App\Form\CommentaryType;
use App\Form\TermType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DictionaryController extends Controller
{
    /**
     * @Route("/termDetail/{id}", name="termDetail")
     */
    public function termDetail($id, Request $request) {
        $termReq= $this->getDoctrine()->getRepository(Term::class);
        $term = $termReq->find($id);

        $terms = $termReq->findBy([], ['term' => 'ASC']);

        $previouscommentary = $term->getCommentaries();

        $commentary = new Commentary();
        $commentaryForm = $this->createForm(CommentaryType::class, $commentary);

        $commentaryForm->handleRequest($request);

        if($commentaryForm->isSubmitted() && $commentaryForm->isValid()) {

            $em = $this->getDoctrine()->getManager();

            $commentary->setTerm($term);
            $commentary->setUser($this->getUser());
            $commentary->setDateCreated(new \DateTime());

            $em->persist($commentary);

            $em->flush();

            $this->addFlash("success", "Votre commentaire a bien été ajouté !");

            return $this->redirectToRoute('termDetail', ["id" => $term->getId()]);
        }


        return $this->render('dictionary/detail.html.twig', [
            'term' => $term,
            'terms' => $terms,
            'previouscommentary' => $previouscommentary,
            'commentaryForm' => $commentaryForm->createView()
        ]);
    }

    /**
     * @Route("/termAdd", name="termAdd")
     */
    public function termAdd(Request $request) {
        $termReq= $this->getDoctrine()->getRepository(Term::class);
        $term = new Term();
        $termForm = $this->createForm(TermType::class, $term);

        $termForm->handleRequest($request);

        if($termForm->isSubmitted() && $termForm->isValid()) {

            $datetime = new \DateTime();
            $timestamp = $datetime->getTimestamp();

            $em = $this->getDoctrine()->getManager();
            $term->setVotesCount(0);
            $term->setEditedDate($timestamp);
            $term->setCreatedDate($timestamp);
            $em->persist($term);
            $em->flush();

            $this->addFlash("success", "Votre terme a bien été ajouté !");


            return $this->redirectToRoute('termDetail', ["id" => $term->getId()]);
        }

        return $this->render('dictionary/adterm.html.twig', [
            "termForm" => $termForm->createView()
        ]);
    }

    /**
     * @Route("/termUpdate/{id}", name="termUpdate")
     */
    public function termEdit(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();
        $repoTerm = $em->getRepository(Term::class);
        $term = $repoTerm->find($id);

        $termForm = $this->createForm(TermType::class, $term);

        $termForm->handleRequest($request);
        if($termForm->isSubmitted() && $termForm->isValid()) {
            if (!$term) {
                throw $this->createNotFoundException(
                    'Pas de terme trouvé pour l\'id '.$id
                );
            }

            $em->persist($term);
            $em->flush();
            $this->addFlash("success", "Votre terme a bien été modifiée !");

            return $this->redirectToRoute('termDetail', ["id" => $term->getId()]);
        }

        return $this->render('dictionary/update.html.twig', [
            "termForm" => $termForm->createView(),
            "term" => $term
        ]);

    }

    /**
     * @Route("/termDelete/{id}", name="termDelete")
     */
    public function termDelete(Request $resquest, $id) {

        $em = $this->getDoctrine()->getManager();
        $term = $em->getRepository(Term::class)->find($id);

        $em->remove($term);
        $em->flush();

        $this->addFlash("success", "Votre terme a bien été suprimée !");

        return $this->redirectToRoute('main');

    }

    /**
     * @Route("/termSearch", name="termSearch")
     */
    public function termSearch(Request $req) {

        $termRepo = $this->getDoctrine()->getRepository(Term::class);
        $keyword = $req->query->get("keyword");

        $terms = $termRepo->findSearchTerms($keyword);

        return $this->render("dictionary/search.html.twig", ["terms" => $terms]);

    }

    /**
     * @Route("/term/{id}", name="rateterm")
     */
    public function rateterm($id) {
        $em = $this->getDoctrine()->getManager();
        $repoTerm = $em->getRepository(Term::class);
        $term = $repoTerm->find($id);
        $term->setVotesCount($term->getVotesCount()+1);

        $em->persist($term);
        $em->flush();

        return $this->redirectToRoute('termDetail', ["id" => $term->getId()]);

    }

}

templates/dictionary/ad.html.twig
{% extends 'layout.html.twig' %}

{%  block main %}

    <div class="row">
        <div class="col">
            <div style="text-align: center;">
                <div class="card" style="width: 60%; margin: auto; margin-top: 10%; padding: 5%;">

                    <h4 style="color: brown;">Ajout du terme</h4>
                    <div style="height: 450px;">
                        <div style="overflow: scroll; height: 100%; margin-right: 5%; margin-top: 5%; width: 100%;">
                            <div style="padding-bottom: 10%;">
                                {{ form_start(termForm) }}
                                {{ form_widget(termForm) }}
                                <button class="btn btn-primary" type="submit">Enregistrer</button>
                                {{ form_end(termForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/dictionary/adterm.html.twig
{% extends 'layout.html.twig' %}

{%  block main %}

    <div class="row">
        <div class="col">
            <div style="text-align: center;">
                <div class="card" style="width: 60%; margin: auto; margin-top: 10%; padding: 5%;">

                    <h4 style="color: brown;">Ajout du terme</h4>
                    <div style="height: 450px;">
                        <div style="overflow: scroll; height: 100%; margin-right: 5%; margin-top: 5%; width: 100%;">
                            <div style="padding-bottom: 10%;">
                                {{ form_start(termForm) }}
                                {{ form_widget(termForm) }}
                                <button class="btn btn-primary" type="submit">Enregistrer</button>
                                {{ form_end(termForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/dictionary/detail.html.twig
{% extends 'layout.html.twig' %}

{%  block main %}

    <div class="row">
        <div class="col">
                <div style="text-align: center;">
                    <div class="card" style="width: 90%; margin: auto; margin-top: 10%; padding-bottom: 5%;">
                        {%  if app.user %}
                        <p style="text-align: right; margin-top: 5px; margin-right: 5px;"> <a href="{{ path('rateterm', {"id": term.id}) }}" class="btn btn-outline-warning">{{ term.votescount}} <i style="color: #FFEB3B;" class="fas fa-star"></i></a></p>
                        {% endif %}

                        <h4 style="color: brown; margin-bottom: 10%;">Terme : {{ term.term }}</h4>
                        <div>
                            {% if (term.definiton1 is defined) or (term.definition2 is defined) %}
                            <h4>Définition(s)</h4>
                            <p>{{ term.definition1 }}</p>
                            {% if term.definition2 %}
                            <p>{{ term.definition2 }}</p>
                            {% endif %}
                            {% endif %}

                            {% if term.example %}
                            <h4>Exemple</h4>
                            <p>{{ term.example }}</p>
                            {% endif %}

                            {% if term.translation %}
                            <h4>Traduction </h4>
                            <p>{{ term.translation }}</p>
                            {% endif %}

                            {% if term.variation %}
                            <h4>Variation</h4>
                            <p>{{ term.variation }}</p>
                            {% endif %}

                            {% if term.pronunciation %}
                            <h4>Prononciation</h4>
                            <p>{{ term.pronunciation}}</p>
                            {% endif %}

                            {%  if term.origin %}
                            <h4>Origine</h4>
                            <p>{{ term.origin }}</p>
                            {% endif %}
                        </div>

                        {%  if app.user %}
                        <div class="row">
                            <div class="col">
                                <a href="{{ path('termUpdate',{"id": term.id}) }}" class="btn btn-primary"><i class="fas fa-edit"></i> Modifier</a>
                            </div>
                            <div class="col">
                                <a href="{{ path('termDelete', {"id": term.id }) }}" style="color: white;" class="btn btn-danger"><i class="fas fa-trash"></i> Supprimer</a>
                            </div>
                        </div>
                        {% endif %}
                </div>


                <div class="card" style="width: 90%; margin: auto; margin-top: 10%; padding-bottom: 5%;">
                    <div style="padding: 5%;">
                        <h4>Derniers commentaires</h4>
                        {% for commentary in previouscommentary %}
                            <div style="background-color: rgba(0,0,0,0.1); padding-left: 2%; padding-top: 2%; padding-right: 2%; border-radius: 15px;">
                                <p style="text-align: left;">{{ commentary.note }}</p>
                                <p style="text-align: right; font-size: 12px;"><em>Posté par {{ commentary.user.username }} le {{ commentary.dateCreated | date("H:i d-m-Y") }}</em></p>
                            </div>
                        {% else %}
                            <p>Il n'y a pas de commentaires</p>
                        {%  endfor %}

                    </div>
                    {%  if app.user %}
                            <div style="padding: 5%;">
                                <hr>
                                <h4>Laisser un commentaire</h4>

                                {{ form_start(commentaryForm) }}
                                {{ form_widget(commentaryForm) }}
                                <button class="btn btn-primary" type="submit">Enregistrer</button>
                                {{ form_end(commentaryForm) }}

                            </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-4">
            <div style="overflow: scroll; height: 70vh; margin-right: 5%; margin-top: 20%;">
                <h3 style="text-align: center">Liste des termes : </h3>
                <ul class="list-group">
                    {% for term in terms %}
                        <a  href="{{ path('termDetail', {'id': term.id}) }}" class="blocka">
                            <li class="list-group-item blocklink">
                                <div class="row">
                                    <div class="col">
                                        <p style="text-align: left;">{{ term.term }}</p>
                                    </div>
                                    <div class="col">
                                        <p style="text-align: right;">{{ term.votescount}} <i style="color: #FFEB3B;" class="fas fa-star"></i></p>
                                    </div>
                                </div>
                            </li>
                        </a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/dictionary/search.html.twig
{% extends 'layout.html.twig' %}

{%  block main %}

    <div class="row">
        <div class="col">
            <div style="text-align: center;">
                <div class="card" style="width: 60%; margin: auto; margin-top: 10%; padding: 5%;">

                    <h4 style="color: brown;">Liste des termes trouvés</h4>
                    <div style="height: 450px;">
                        <div style="overflow: scroll; height: 100%; margin-right: 5%; margin-top: 5%; width: 100%;">
                            <div style="padding-bottom: 10%;">
                                {% for term in terms %}
                                    <a  href="{{ path('termDetail', {'id': term.id}) }}" class="blocka">
                                        <li class="list-group-item blocklink">
                                            <div class="row">
                                                <div class="col">
                                                    <p style="text-align: left;">{{ term.term }}</p>
                                                </div>
                                                <div class="col">
                                                    <p style="text-align: right;">{{ term.votescount}} <i style="color: #FFEB3B;" class="fas fa-star"></i></p>
                                                </div>
                                            </div>
                                        </li>
                                    </a>
                                {%  endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/dictionary/update.html.twig
{% extends 'layout.html.twig' %}

{%  block main %}

    <div class="row">
        <div class="col">
            <div style="text-align: center;">
                <div class="card" style="width: 60%; margin: auto; margin-top: 10%; padding: 5%;">

                    <h4 style="color: brown;">Modification du terme</h4>
                    <div style="height: 450px;">
                        <div style="overflow: scroll; height: 100%; margin-right: 5%; margin-top: 5%; width: 100%;">
                            <div style="padding-bottom: 10%;">
                                {{ form_start(termForm) }}
                                {{ form_widget(termForm) }}
                                <button class="btn btn-primary" type="submit">Enregistrer</button>
                                {{ form_end(termForm) }}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}